- name: Installation de MySQL serveur
  ansible.builtin.apt:
    name: default-mysql-server
    state: present
  become: yes

- name: Installation MySQLDB python
  ansible.builtin.apt:
    name: python3-mysqldb
    state: present
  become: yes

- name: Creation de staging db
  mysql_db:
    name: "{{ stag_db_name }}"
    state: present
  become: yes

- name: Creation de staging user
  mysql_user:
    name: "{{ stag_user }}"
    password: "{{ mysql_stag_pass }}"
    priv: "*.*:ALL"
    host: "%"
    state: present
  become: yes
  vars:
    column_case_sensitive: false

- name: Creation de production db
  mysql_db:
    name: "{{ prod_db_name }}"
    state: present
  become: yes

- name: Creation de production user
  mysql_user:
    name: "{{ prod_user }}"
    password: "{{ mysql_prod_pass }}"
    priv: "*.*:ALL"
    host: "%"
    state: present
  become: yes
  notify:
    - restart_mysql
  vars:
    column_case_sensitive: false
