all:
  hosts:
    vm-omar-prod-01:
      ansible_host: 152.228.212.65
      ansible_user: debian

    vm-omar-stag-01:
      ansible_host: 152.228.211.237
      ansible_user: debian

  children:
    webservers:
      hosts:
        vm-omar-prod-01: ~
        vm-omar-stag-01: ~

    dbservers:
      hosts:
        vm-omar-prod-01: ~
        vm-omar-stag-01: ~

    staging:
      hosts:
        vm-omar-stag-01: ~

    production:
      hosts:
        vm-omar-prod-01: ~
